language: node_js
dist: xenial
node_js:
  - "8"
  - "10"
  - "12"
  - "13"
git:
  depth: 5
  quiet: true
before_install:
  - rm -rf .git
  - npm set audit false
install:
  - chmod +x ./perf-test.sh
  - chmod +x ./bin/yq
script:
  - ./perf-test.sh
cache:
  directories:
  - node_modules
  timeout: 60