language: node_js
dist: xenial
node_js:
  - "8"
  - "10"
  - "12"
git:
  depth: 5
  quiet: true
before_install:
  - rm -rf .git
  - npm set audit false
install:
  - git clone https://github.com/theme-suka/hexo-theme-unit-test
  - cd hexo-theme-unit-test
  - git clone https://github.com/hexojs/hexo-theme-landscape themes/landscape --depth=1
  - npm i > /dev/null
  - cd ..
script:
  - chmod +x ./perf-test.sh
  - chmod +x ./bin/yq
  - ./perf-test.sh
cache:
  directories:
  - node_modules
  timeout: 60